-- LDAPA Seed Data - Sample Providers for Development

INSERT INTO providers (id, name, organization, service_types, specializations, serves_ages, address, city, state, zip_code, region, cost_tier, insurance_accepted, accepts_medicaid, cost_notes, phone, email, website, description, verification_status, last_verified_at, staff_notes) VALUES
('p1', 'Dr. Sarah Chen', 'Child Development Associates', '["evaluator"]', '["dyslexia","adhd","general_ld"]', '["children","adolescents"]', '4500 Forbes Ave, Suite 200', 'Pittsburgh', 'PA', '15213', 'Pittsburgh Metro', 'low_cost', 1, 1, 'Sliding scale available for families under $50k income', '(412) 555-0142', 'schen@childdevassociates.example.com', 'https://www.childdevassociates.example.com', 'Licensed psychologist specializing in learning disability evaluations for children and teens. Offers comprehensive assessments including cognitive, academic, and behavioral testing. Over 15 years of experience working with diverse populations.', 'verified', '2026-01-15T10:00:00', 'Excellent provider. Very responsive to referrals.'),

('p2', 'Pittsburgh Reading Institute', NULL, '["tutor","nonprofit_org"]', '["dyslexia","general_ld"]', '["children","adolescents"]', '301 S Highland Ave', 'Pittsburgh', 'PA', '15232', 'Pittsburgh Metro', 'free', 0, 0, 'Free for families meeting income guidelines. Donations welcome.', '(412) 555-0298', 'info@pghreading.example.org', 'https://www.pghreading.example.org', 'Nonprofit reading tutoring program for students with learning disabilities. Uses evidence-based Orton-Gillingham approach. Free for families meeting income guidelines. Serves over 200 students annually.', 'verified', '2026-02-01T14:30:00', NULL),

('p3', 'Dr. Michael Torres', 'Western PA Behavioral Health', '["therapist"]', '["adhd","general_ld"]', '["children","adolescents","adults"]', '1000 Liberty Ave, Suite 800', 'Pittsburgh', 'PA', '15222', 'Pittsburgh Metro', 'standard', 1, 0, NULL, '(412) 555-0467', 'mtorres@wpabh.example.com', 'https://www.wpabh.example.com', 'Licensed clinical psychologist providing therapy for individuals with ADHD and learning disabilities. Specializes in cognitive behavioral therapy and executive function coaching. Accepts most major insurance plans.', 'verified', '2025-12-20T09:00:00', NULL),

('p4', 'Learning Bridges Advocacy', NULL, '["advocate","nonprofit_org"]', '["iep_504","general_ld"]', '["children","adolescents"]', '500 Grant St, Suite 300', 'Pittsburgh', 'PA', '15219', 'Pittsburgh Metro', 'sliding_scale', 0, 0, 'Free initial consultation. Sliding scale based on income for ongoing advocacy.', '(412) 555-0589', 'help@learningbridges.example.org', 'https://www.learningbridges.example.org', 'Nonprofit educational advocacy organization helping families navigate IEP and 504 plan processes. Provides trained advocates who attend school meetings with families. Free initial consultation.', 'verified', '2026-01-28T11:00:00', 'Great resource for families. Very knowledgeable about PA education law.'),

('p5', 'Dr. Amanda Wright', 'Allegheny Evaluation Center', '["evaluator","school_psychologist"]', '["dyslexia","dyscalculia","dysgraphia","adhd"]', '["children","adolescents"]', '2000 Technology Dr, Suite 150', 'Pittsburgh', 'PA', '15219', 'Pittsburgh Metro', 'standard', 1, 1, NULL, '(412) 555-0721', 'awright@allegeval.example.com', 'https://www.allegeval.example.com', 'Board-certified school psychologist offering comprehensive psychoeducational evaluations. Specializes in identifying specific learning disabilities including dyslexia, dyscalculia, and dysgraphia. Reports include detailed recommendations for school accommodations.', 'verified', '2026-02-10T16:00:00', NULL),

('p6', 'Erie Learning Center', NULL, '["tutor","clinic"]', '["dyslexia","general_ld"]', '["children","adolescents"]', '123 State St', 'Erie', 'PA', '16501', 'Northwest PA', 'low_cost', 0, 0, '$25-50 per session based on family income', '(814) 555-0334', 'info@erielearning.example.com', 'https://www.erielearning.example.com', 'Community-based learning center offering individualized tutoring for students with learning disabilities. Uses multisensory teaching methods. Small group and one-on-one sessions available.', 'verified', '2025-11-15T10:00:00', NULL),

('p7', 'Keystone Adult LD Services', NULL, '["evaluator","therapist","support_group"]', '["adult_ld","adhd","workplace_accommodations"]', '["adults"]', '789 Main St, Suite 400', 'Harrisburg', 'PA', '17101', 'Central PA', 'sliding_scale', 1, 0, 'Sliding scale $50-150 per session', '(717) 555-0892', 'contact@keystoneadultld.example.com', 'https://www.keystoneadultld.example.com', 'Specialized services for adults with learning disabilities. Offers evaluations, individual therapy, and support groups. Expertise in workplace accommodation planning and career counseling for adults with LD.', 'verified', '2026-01-05T13:00:00', NULL),

('p8', 'Philly Special Ed Advocates', NULL, '["advocate"]', '["iep_504","general_ld"]', '["children","adolescents"]', '1500 Market St, Suite 1200', 'Philadelphia', 'PA', '19102', 'Philadelphia Metro', 'free', 0, 0, 'Completely free for families in Philadelphia County', '(215) 555-0456', 'info@phillyspedadvocates.example.org', 'https://www.phillyspedadvocates.example.org', 'Free special education advocacy services for families in Philadelphia. Helps families understand their rights, navigate IEP meetings, and ensure children receive appropriate services. Bilingual services available (English/Spanish).', 'unverified', NULL, 'New provider - needs verification call'),

('p9', 'Central PA Dyslexia Tutoring', NULL, '["tutor"]', '["dyslexia"]', '["children","adolescents"]', '200 College Ave', 'State College', 'PA', '16801', 'Central PA', 'standard', 0, 0, NULL, '(814) 555-0123', 'info@centralpady.example.com', NULL, 'Orton-Gillingham certified tutors providing one-on-one reading instruction for students with dyslexia. Evening and weekend appointments available.', 'unverified', NULL, NULL),

('p10', 'Southwest PA Support Network', NULL, '["support_group","nonprofit_org"]', '["general_ld","adhd"]', '["children","adolescents","adults"]', '50 S Main St', 'Washington', 'PA', '15301', 'Southwest PA', 'free', 0, 0, 'All groups and workshops are free', '(724) 555-0678', 'swpasupport@example.org', NULL, 'Parent support groups and workshops for families affected by learning disabilities. Monthly meetings in Washington County. Annual conference. Resource library available.', 'verified', '2025-10-01T10:00:00', 'Very active community group. Good for referrals.'),

('p11', 'Dr. James Park', NULL, '["evaluator"]', '["adhd","general_ld"]', '["adults"]', '400 Penn Ave', 'Pittsburgh', 'PA', '15222', 'Pittsburgh Metro', 'standard', 1, 0, NULL, '(412) 555-0999', 'jpark@example.com', NULL, 'Adult ADHD and learning disability specialist. Comprehensive evaluations with detailed reports for workplace accommodations and educational accommodations.', 'unverified', NULL, 'Referred by Dr. Torres - needs verification'),

('p12', 'Lehigh Valley Learning Lab', NULL, '["tutor","clinic"]', '["dyslexia","dyscalculia","general_ld"]', '["children"]', '700 Hamilton St', 'Allentown', 'PA', '18101', 'Lehigh Valley', 'low_cost', 0, 0, '$30-60 per session', '(610) 555-0234', 'info@lvlearninglab.example.com', 'https://www.lvlearninglab.example.com', 'After-school and summer tutoring programs for elementary students with identified learning disabilities. Certified teachers use structured literacy and multisensory math approaches.', 'archived', '2025-06-15T10:00:00', 'Archived - temporarily closed for renovation. Check back March 2026.');

-- Default admin user (password: admin123 - change in production!)
-- bcrypt hash of 'admin123'
INSERT INTO admin_users (id, email, password_hash, name) VALUES
('admin1', 'admin@ldapa.org', '$2b$12$UztW.0/LOix.pUQCWUsX6uEhrePdvnDf2WgXr9CZebWSvrr8x8JNS', 'LDAPA Admin');
